server:
  servlet:
    context-path: /
  port: 8098

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gg.model.*.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false